baseURL = "http://example.org/"
languageCode = "en-us"
title = "BLAM_lab"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Research"
      url = "research"
    [[menu.header]]
      weight = 3
      name = "Blog"
      url = "blog"
    [[menu.header]]
      weight = 4
      name = "About"
      url = "about"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "work"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "blog"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [params.slider]
    enable = true
    title = "Belief, Learning & Memory Laboratory"
    subtitle = "We love Brains<br/>We do research and that's pretty cool"
    bgImage = "img/slider-bg.jpg"
    btnText = "Discover Our Research Projects"
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.jpg"
    title = "About Us"
    italic = "Delusions are odd beliefs. They accompany many psychiatric illnesses, notably schizophrenia. A major challenge is to understand delusions in terms of changes in brain function."
    paragraph = "Our lab attempts to meet this challenge by investigating the neural basis of human associative learning and belief formation, relating these processes to the formation of delusional beliefs."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"


 


  [params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/feature-bg.jpg"
    content = "Dr. Corlett’s findings have shaped the development of a novel mechanistic model of delusion formation."
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
    [params.call.button]
      url = "#"
      text = "tell us your story"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"